server.port=8080

google.api.key=AIzaSyCp3OGWjzz3VF_v3p0H--HnT-xpBDVv0Mg
google.api.model=gemini-2.0-flash

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=tanmay123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=MySecretKey123456
