spring.config.import=optional:file:.env[.properties],optional:file:backend/.env[.properties]

server.port=8080
openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.api.model=meta-llama/llama-3.3-70b-instruct:free

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret (for login later)
jwt.secret=MySecretKey123456
